### ISSUE TITLE
Revisit error handling

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-index#13]
Following on #12, IMHO, constructor should confirm that CSV file exists, and that s5cmd is available where expected, and - if not - at least raise exception.

We should also discuss if it may also make sense to allow users to point to their own s5cmd and initialize index with their own CSV file.

**Comment by vkt1414** [comment]
I'm with you on raising an error (which is already done at the pip installation step but I dont mind another checkpoint) but I personally do not like to download the csv or s5cmd after that. The code should break and user must install the package again.

**Comment by vkt1414** [comment]
Closing this as it is not relevant anymore.
