### ISSUE TITLE
Revisit testing

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-index#14]
Currently, testing is set up in such a way that can be executed from the source tree with the command below

`python -m unittest -vv tests/idcindex.py`

Need to investigate whether this is an expected/preferred mechanism for running the tests, and if it should be updated. It is definitely a very straightforward and convenient mechanism IMHO.

**Comment by jcfr** [comment]
This can be closed.

While `idcindex.py` is still based on the `unittest` module, it can be run through pytest as demonstrated through the integration of https://github.com/ImagingDataCommons/idc-index/pull/32

Relevant notes copied from from the pull-request description:

> Requirements to have test filename starting with `test_*` has been relaxed, and configuration updated to support running traditional `unitest` tests or `pytest` ones.
> See https://docs.pytest.org/en/latest/how-to/unittest.html
