### ISSUE TITLE
pip install from the source tree does not work

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-index#15]
```python
!git clone https://github.com/ImagingDataCommons/idc-index
!cd idc-index && git checkout 0.2.6
!python -m pip install -e ./idc-index


from idc_index import index

client = index.IDCClient()
```

This results in the import error

<img width="690" alt="image" src="https://github.com/ImagingDataCommons/idc-index/assets/313942/ffc1c8a7-c997-409e-a403-64b4d6e03cbf">

I would think it should work?

Demo notebook (I deleted and reconnected to VM between the two experiments): https://colab.research.google.com/drive/1OdLfAAxmSYFJAZ63_L0W6fvVFw2KbiJX?usp=sharing

**Comment by vkt1414** [comment]
!git clone https://github.com/ImagingDataCommons/idc-index
!cd idc-index && git checkout 0.2.6

pip install .

get out of the idc-index directory to force importing from python paths rather than local directory..
and then importing and initializing clients worked for me.

![image](https://github.com/ImagingDataCommons/idc-index/assets/115020590/66af26f9-3deb-4734-93bc-9d1d8546238e)

**Comment by jcfr** [comment]
This can be closed, following the integration of https://github.com/ImagingDataCommons/idc-index/pull/32 

```
$ mkvirtualenv -p python3.9  test-install-from-source
$ git clone https://github.com/ImagingDataCommons/idc-index.git /tmp/idc-index
$ pip install idc-index
$ python -c "from idc_index import index; client = index.IDCClient()"

Index file not found. Downloading latest version of the index file. This will take a minute or so.
Index file downloaded.
```

Note that in the example above, the `-e` is not specified. This is on purpose as creating a editable install would work to disable build isolation as described at https://scikit-build-core.readthedocs.io/en/latest/configuration.html#editable-installs

Last, in the context of notebook and tutorials, I now recommend to simply install the wheel.

**Comment by jcfr** [comment]
While running the test described above in https://github.com/ImagingDataCommons/idc-index/issues/15#issuecomment-1928560437, I also noticed that the output of `s5cmd --help` was always displayed.

This is now fixed in:
* https://github.com/ImagingDataCommons/idc-index/pull/36
