### ISSUE TITLE
Making sure to resolve properly

### ISSUE THREAD

**Issue by vkt1414** [ImagingDataCommons/idc-index#2]
@fedorov I'm looking more closely at the changes you made. 
While I feel those changes work great from IDCBrowser standpoint of view, I think if users want to use this package outside of the extension, I think we should rework on the logic. 
Relying only on patient_id for get_dicom_studies, in my opinion may not be a good idea, as it may be possible for two different collections that have the same patient_id. similarly for get_dicom_studies and get_dicom_series.
I think we should allow all filters available in the hierarchy. For  get_dicom_studies let us allow collection_id, studyInstanceUID arguments also in addition to patient_id. Similarly for get_dicom_series, let us allow collection_id, patient_id, studyInstanceUID, and seriesInstanceuid.
What do you think?

**Comment by fedorov** [comment]
I suggest we keep the API minimalistic for now, migrate SlicerIDCBrowser to use idc-index, and revisit this based on early experience/user feedback. I prefer to keep the API minimal, and not grow the list of parameters without real need. With the existing functionality, use can do what you say, it will just take several API calls.

**Comment by vkt1414** [comment]
Sure! I'll close this. We can revisit this later if needed.
