### ISSUE TITLE
Add an option to download into user-defined hierarchy

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-index#22]
Since we have patient/study/series etc in the index, we can create folders on the fly and organize files as such. This feature can also be useful in Slicer browser. Need to think how to configure the path structure, or easier just freeze it with specific choices.

**Comment by vkt1414** [comment]
One idea could be we make download directory argument optional..and by default, we can download the series into patient/study/series_id hierarchy

**Comment by LennyN95** [comment]
I suggest having a look at the [DataOrganizer](https://github.com/MHubAI/mhubio/blob/main/mhubio/modules/organizer/DataOrganizer.py) module I build in mhubio for some inspiration ;)

**Comment by LennyN95** [comment]
The idea is to define a path template like `my/dir/[PatientID]/[SeriesInstanceUID]`, where the variables in brackets will resolve to values from the columns. This then is resolved for the subset of data (e.g., returned by a sql_query) and resolved per row before the download.

**Comment by vkt1414** [comment]
@fedorov 

`thedicomsort` allows the use of any attribute in the DICOM header. So I think we cannot use Steve's implementation directly. I' think we could allow any of the following attributes in any order.

collection_id,
patientId,
seriesInstanceUID,
StudyInstanceUID, 
studyDescription,
and Modality


This is similar to tcia's 'classic' implementation. Except, we allow studyDescription, Modality, and the attributes to be in any order. The users are expected to provide a similar string template as dicomsort in the following example.

 `%PatientName-%Modality%StudyID-%StudyDescription-%StudyDate/%SeriesNumber_%SeriesDescription`

What do you think?

**Comment by LennyN95** [comment]
I was just thinking about this, why not just downloading the data into a single folder and then running dicomsort in-place? Thesicomsort could even be an (optional) dependency of idc-index :)

**Comment by fedorov** [comment]
> `thedicomsort` allows the use of any attribute in the DICOM header. So I think we cannot use Steve's implementation directly. I' think we could allow any of the following attributes in any order.

Yes, right - we would only allow the use of the attributes that are present in our index!

> 
I was just thinking about this, why not just downloading the data into a single folder and then running dicomsort in-place? Thesicomsort could even be an (optional) dependency of idc-index :)

For a small cohort, this would work just fine, but it is not unreasonable to have cohorts that will have 10s of TBs. Moving that much data in place will not be quick. Most important, it is completely unnecessary, since we can download in-place.
