### ISSUE TITLE
Add command-line python tools to assist with download

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-index#33]
I think it would be good to have a command-line wrapper of the download API that would allow user to download content specified by either manifest or DICOM UIDs. 

Inspiration for this suggestion was this snippet from @LennyN95 in [this tutorial](https://github.com/MHubAI/documentation/blob/main/tutorials/run_totalsegmentator_on_idc_collection/mhub_tutorial_001.md) that utilizes `s5cmd`:

```bash
$ s5cmd --no-sign-request --endpoint-url https://s3.amazonaws.com \
  cp 's3://idc-open-data/8e4ccba1-74f4-4ffa-93f1-2a0263c8c9cf/*' $in && \
  s5cmd --no-sign-request --endpoint-url https://s3.amazonaws.com \
  cp 's3://idc-open-data/7271ab1d-bb03-4ca9-9457-dabcafd4d33f/*' $in && \
  s5cmd --no-sign-request --endpoint-url https://s3.amazonaws.com \
  cp 's3://idc-open-data/5541d783-4c8b-4d1b-8eae-99a868012082/*' $in && \
  echo "Downloaded $(ls $in | wc -l) files"
```

It should be very easy to have something like this, with `download-from-idc` script added to the path on package install

```bash
$ download-from-idc --destinationDir . \
  1.2.840.113654.2.55.68425808326883186792123057288612355322 \
  1.2.840.113654.2.55.89933508291954731667890414920476511765 \
  1.2.840.113654.2.55.174144834924218414213677353968537663991 
```

For the reference, this is how python command-line tools are implemented in `pyradiomics`: https://github.com/AIM-Harvard/pyradiomics/blob/master/radiomics/scripts/__init__.py.

**Comment by jcfr** [comment]
> to have a command-line wrapper

https://github.com/ImagingDataCommons/idc-index/pull/32 already provide a wrapper `s5cmd` as installed "python script".

Once it is integrated, I suggest the following:
* Rename `idc_index/index.py` to `idc_index/client.py`
* Add `idc_index/cli.py` with function like `download_from()` `upload_to()`, `main()` ... then you would just add the following to `pyproject.toml`:

```diff
[project.scripts]
s5cmd = "idc_index.s5cmd:s5cmd"
+download-from-idc = "idc_index.cli:download_from"
+upload-to-idc = "idc_index.cli:upload_to"
+ idc = "idc_index.cli:main"
```

You may want to revisit the "executable" name to be prefixed by `idc`


For argument parsing, I suggest to use `click` (See https://click.palletsprojects.com/), I can provide example as well.

The cli prarts, could also be optional and made available through `idc-index[cli]` ...

**Comment by fedorov** [comment]
And once we have that command line tool, looks like it might be easy to make a GUI app around it: https://github.com/chriskiehl/Gooey.
