### ISSUE TITLE
Fix wheel testing step

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-index#38]
Currently is failing here: https://github.com/ImagingDataCommons/idc-index/actions/runs/7794403398/job/21255678157#step:3:386

Maybe because of the incorrect assumption about the manifest files location? Those tests were put together and tested for unittest local testing.

**Comment by jcfr** [comment]
Thanks for the report, I will have a look later this evening

**Comment by fedorov** [comment]
@jcfr I really wanted to see the entire process working, in case we need your help with anything else, so I went ahead with the fix in #39 - this way if you still have time, you can use it to review any other packaging/setup related issue! 

Would you like to be added to the list of `idc-index` owners/maintainers on PyPI?

One thing that bothers me is that CI tests succeeded, but wheel packaging tests failed. This could be a problem potentially!

Publish step failed initially, since we did had to add the workflow on PyPI, but after that it succeeded, and 0.3.1 is live: https://pypi.org/project/idc-index/.

![image](https://github.com/ImagingDataCommons/idc-index/assets/313942/46d872f1-44c6-45e3-958c-a3a940faaba5)
