### ISSUE TITLE
Consider creating a Python package called `idc-index-data`

### ISSUE THREAD

**Issue by jcfr** [ImagingDataCommons/idc-index#49]
Creating a python package called `idc-index-data` (or similar name) with a date based versioning scheme similar to `certifi`[^1] would avoid bloating the python package index (PyPI) with duplicate of the index data each time there is a release of `idc-index`.

[^1]: https://pypi.org/project/certifi/

**Comment by fedorov** [comment]
> Once such project is created

Done! 🙏

**Comment by jcfr** [comment]
Closing. Project `idc-index-data` has been updated and corresponding package uploaded:
* https://github.com/ImagingDataCommons/idc-index/pull/48#issuecomment-1989568612
* https://pypi.org/project/idc-index-data/
