### ISSUE TITLE
Enable building preview of pull-request documentation

### ISSUE THREAD

**Issue by jcfr** [ImagingDataCommons/idc-index#82]
See https://docs.readthedocs.io/en/stable/guides/pull-requests.html

**Comment by jcfr** [comment]
<img width=50% src="https://github.com/ImagingDataCommons/idc-index/assets/219043/2b3c8069-9ba9-4f41-b9a8-f5123ff98957"/>

**Comment by jcfr** [comment]
After rebasing and force pushing the branch associated with https://github.com/ImagingDataCommons/idc-index/pull/83, we can confirm the preview documentation is built:

![image](https://github.com/ImagingDataCommons/idc-index/assets/219043/d03ef646-6f06-4df2-a29a-c85786a4337f)

**Comment by fedorov** [comment]
@jcfr but did you figure out why the latest version for `main` was not built? In any case, I am going to merge #83 and see if this resolves the issue.

**Comment by fedorov** [comment]
unfortunately, "latest" version does not work, as noted in https://github.com/ImagingDataCommons/idc-index/pull/83#issuecomment-2118348362.

**Comment by fedorov** [comment]
Preview for this PR doesn't work either! https://github.com/ImagingDataCommons/idc-index/pull/84

**Comment by jcfr** [comment]
I just rebased and force-pushed the corresponding branch:

<img width=50% src="https://github.com/ImagingDataCommons/idc-index/assets/219043/2c1ca023-744c-439a-b40b-58902785abb8"/>
