### ISSUE TITLE
Tried to use tutorial from the Pypy page and came up with error

### ISSUE THREAD

**Issue by oohtmeel1** [ImagingDataCommons/idc-index#92]
Two weeks ago I tried to use the IDC package and it worked well.
But today I went to use it and obtained this error :
TypeError: seriesInstanceUID must be a string or list of strings

So I tried to use one of the example pieces of code that I know should work. 
And that was broken too. (Same error)
I tried to use 
from idc_index import index

client = index.IDCClient()

query = """
SELECT
  SeriesInstanceUID
FROM
  index
WHERE
  Modality = 'MR'
"""

selection_df = client.sql_query(query)

client.download_from_selection(
    seriesInstanceUID=selection_df["SeriesInstanceUID"].values[:10], downloadDir="."
)

Not sure if it is just me or not.

**Comment by vkt1414** [comment]
Hi @oohtmeel1 , thank you reporting the error in our README file! I see that `selection_df["SeriesInstanceUID"].to_list()[:10]` returns an array. But we currently support only a string or list of strings. Please use something like `selection_df["SeriesInstanceUID"].to_list()[:10]` or `list(liver_mr_selection_sql['SeriesInstanceUID'].values[:10])`instead.

Here are a few tutorials that @fedorov has put together to learn more about idc-index.
https://github.com/ImagingDataCommons/IDC-Tutorials/tree/master/notebooks/getting_started

I'll update the README.md file ASAP.

**Comment by fedorov** [comment]
Thank you for reporting the issue @oohtmeel1!

**Comment by oohtmeel1** [comment]
No problem. I like the IDC package. I think it is super useful.
Thank you for fixing the readme.

**Comment by vkt1414** [comment]
We appreciate your feedback @oohtmeel1! Please feel free to let us know of any other features you wish were present in idc-index.
